//
// Created by Z-Sabine on 2018/10/22.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
#include "CheckAuthenticate.h"
/* Header for class com_sabinetek_swiss_sdk_SDKHelper */
#define TAG    "SDKHelper"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO,TAG,__VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR,TAG,__VA_ARGS__)

/*
 * Class:     com_sabinetek_swiss_sdk_SDKHelper
 * Method:    checkAuthenticate
 * Signature: (J)Z
 */
extern "C"
JNIEXPORT jboolean JNICALL Java_com_sabinetek_swiss_sdk_SDKHelper_checkAuthenticate
        (JNIEnv *env, jclass jclazz, jlong native_pointer) {
    CheckAuthenticate *checkAuthenticate = reinterpret_cast<CheckAuthenticate *>(native_pointer);
    return static_cast<jboolean>(checkAuthenticate->checkLocak());
}

extern "C"
JNIEXPORT jlong JNICALL Java_com_sabinetek_swiss_sdk_SDKHelper_init
        (JNIEnv *env, jclass jclazz, jobject contextObject, jbyteArray j_appKey, jbyteArray j_appValue) {
    jbyte *data_key = env->GetByteArrayElements(j_appKey, JNI_FALSE);
    jsize keyLength = env->GetArrayLength(j_appKey);
    jbyte *data_value = env->GetByteArrayElements(j_appValue, JNI_FALSE);
    jsize valueLength = env->GetArrayLength(j_appValue);

    jclass native_classs = env->GetObjectClass(contextObject);
    jmethodID mId = env->GetMethodID(native_classs, "getPackageName", "()Ljava/lang/String;");
    jstring pkg_str = static_cast<jstring>(env->CallObjectMethod(contextObject, mId));
    jclass clsstring = env->FindClass("java/lang/String");
    jstring strencode = env->NewStringUTF("utf-8");
    jmethodID mid = env->GetMethodID(clsstring, "getBytes", "(Ljava/lang/String;)[B");
    jbyteArray j_appPkg = (jbyteArray)env->CallObjectMethod(pkg_str, mid, strencode);
    jsize pkgLength = env->GetArrayLength(j_appPkg);
    jbyte* data_pkg = env->GetByteArrayElements(j_appPkg,JNI_FALSE);

    CheckAuthenticate *checkAuthenticate = new CheckAuthenticate(
            reinterpret_cast<uint8_t *>(data_key), keyLength,
            reinterpret_cast<uint8_t *>(data_value), valueLength,
            reinterpret_cast<uint8_t *>(data_pkg), pkgLength);

    env->ReleaseByteArrayElements(j_appKey, data_key, 0);
    env->ReleaseByteArrayElements(j_appValue, data_value, 0);
    env->ReleaseByteArrayElements(j_appPkg, data_pkg, 0);
    return reinterpret_cast<jlong>(checkAuthenticate);
}
